CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    spec TEXT DEFAULT '',
    unit TEXT NOT NULL DEFAULT '件',
    default_price REAL NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT '启用',
    remark TEXT DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS customers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    contact TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    address TEXT DEFAULT '',
    settlement_method TEXT NOT NULL DEFAULT '月结',
    status TEXT NOT NULL DEFAULT '启用',
    remark TEXT DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS warehouses (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS inbound_orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT, order_no TEXT NOT NULL UNIQUE, order_date TEXT NOT NULL,
    supplier TEXT DEFAULT '', warehouse TEXT NOT NULL, operator TEXT DEFAULT '', remark TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT '草稿', total_amount REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS inbound_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER NOT NULL REFERENCES inbound_orders(id),
    product_id INTEGER NOT NULL REFERENCES products(id), quantity REAL NOT NULL, price REAL NOT NULL DEFAULT 0, amount REAL NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS outbound_orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT, order_no TEXT NOT NULL UNIQUE, order_date TEXT NOT NULL,
    customer_id INTEGER NOT NULL REFERENCES customers(id), warehouse TEXT NOT NULL, operator TEXT DEFAULT '', remark TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT '草稿', total_amount REAL NOT NULL DEFAULT 0, settled_amount REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS outbound_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER NOT NULL REFERENCES outbound_orders(id),
    product_id INTEGER NOT NULL REFERENCES products(id), quantity REAL NOT NULL, price REAL NOT NULL DEFAULT 0, amount REAL NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS settlements (
    id INTEGER PRIMARY KEY AUTOINCREMENT, settlement_no TEXT NOT NULL UNIQUE, settlement_date TEXT NOT NULL,
    customer_id INTEGER NOT NULL REFERENCES customers(id), method TEXT NOT NULL DEFAULT '银行转账', amount REAL NOT NULL,
    operator TEXT DEFAULT '', remark TEXT DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS settlement_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT, settlement_id INTEGER NOT NULL REFERENCES settlements(id),
    outbound_order_id INTEGER NOT NULL REFERENCES outbound_orders(id), amount REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS inventory_txns (
    id INTEGER PRIMARY KEY AUTOINCREMENT, txn_date TEXT NOT NULL, warehouse TEXT NOT NULL,
    product_id INTEGER NOT NULL REFERENCES products(id), qty REAL NOT NULL, txn_type TEXT NOT NULL,
    source_no TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS operation_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT, action TEXT NOT NULL, source_no TEXT, operator TEXT DEFAULT '',
    detail TEXT DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
